set_property SRC_FILE_INFO {cfile:D:/ZYNQ_PROJECT/PS/PS_LED_BEEP/PS_LED_BEEP.srcs/constrs_1/new/LED_BEEP.xdc rfile:../../../PS_LED_BEEP.srcs/constrs_1/new/LED_BEEP.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  E19 [get_ports LED1_0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports LED2_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports LED3_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports beep_0]
