# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ZYNQ_PROJECT/PS/PS_LED_BEEP/PS_LED_BEEP.srcs/sources_1/bd/LED_BEEP/ip/LED_BEEP_processing_system7_0_0/LED_BEEP_processing_system7_0_0.xci
# IP: The module: 'LED_BEEP_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ZYNQ_PROJECT/PS/PS_LED_BEEP/PS_LED_BEEP.srcs/sources_1/bd/LED_BEEP/ip/LED_BEEP_processing_system7_0_0/LED_BEEP_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'LED_BEEP_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/ZYNQ_PROJECT/PS/PS_LED_BEEP/PS_LED_BEEP.srcs/sources_1/bd/LED_BEEP/ip/LED_BEEP_processing_system7_0_0/LED_BEEP_processing_system7_0_0.xci
# IP: The module: 'LED_BEEP_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ZYNQ_PROJECT/PS/PS_LED_BEEP/PS_LED_BEEP.srcs/sources_1/bd/LED_BEEP/ip/LED_BEEP_processing_system7_0_0/LED_BEEP_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'LED_BEEP_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
