# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/LED_BEEP.xdc

# Block Designs: bd/LED_BEEP/LED_BEEP.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LED_BEEP || ORIG_REF_NAME==LED_BEEP} -quiet] -quiet

# IP: bd/LED_BEEP/ip/LED_BEEP_processing_system7_0_0/LED_BEEP_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LED_BEEP_processing_system7_0_0 || ORIG_REF_NAME==LED_BEEP_processing_system7_0_0} -quiet] -quiet

# IP: bd/LED_BEEP/ip/LED_BEEP_LED_BEEP_TEST_0_0/LED_BEEP_LED_BEEP_TEST_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==LED_BEEP_LED_BEEP_TEST_0_0 || ORIG_REF_NAME==LED_BEEP_LED_BEEP_TEST_0_0} -quiet] -quiet

# XDC: bd/LED_BEEP/LED_BEEP_ooc.xdc
