# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/LCD_TEST.xdc

# Block Designs: bd/system_lcd/system_lcd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_lcd || ORIG_REF_NAME==system_lcd} -quiet] -quiet

# IP: bd/system_lcd/ip/system_lcd_processing_system7_0_0/system_lcd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_lcd_processing_system7_0_0 || ORIG_REF_NAME==system_lcd_processing_system7_0_0} -quiet] -quiet

# XDC: C:/Users/USER/Desktop/EBAZ4205/XilinxFPGA_SE/EBZA4205/PS_LCD_test/project_1/project_1.gen/sources_1/bd/system_lcd/system_lcd_ooc.xdc
