# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ZYNQ_PROJECT/LCD_test/LCD_test.srcs/sources_1/bd/system_lcd/ip/system_lcd_processing_system7_0_0/system_lcd_processing_system7_0_0.xci
# IP: The module: 'system_lcd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ZYNQ_PROJECT/LCD_test/LCD_test.srcs/sources_1/bd/system_lcd/ip/system_lcd_processing_system7_0_0/system_lcd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_lcd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/ZYNQ_PROJECT/LCD_test/LCD_test.srcs/sources_1/bd/system_lcd/ip/system_lcd_processing_system7_0_0/system_lcd_processing_system7_0_0.xci
# IP: The module: 'system_lcd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ZYNQ_PROJECT/LCD_test/LCD_test.srcs/sources_1/bd/system_lcd/ip/system_lcd_processing_system7_0_0/system_lcd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_lcd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
